### ISSUE TITLE
How you learn?

### ISSUE THREAD

**Issue by asamsulfat** [azzamsa/ama#2]
When we meet, you always have some good story or history to tell.
I Wonder how you learn, and keep remember all of it.

**Comment by azzamsa** [comment]
Hi Nyamuk.

Thanks for your compliment.

As I've explain it to you months ago. I believe you get it already.
But I will put some part of answer here for the matter of history.

I am not the best. But I try everyday to be a better person.

In the matter of remembrance. I don't try to remember all of things I
learn/read. When you love something, you will automatically remember
it. It's like how you can tell people even the most detailed part of
things you love. I try to limit my focus. So all things that I always
told you is never going too far from my interest.

*Ars longa, vita brevis*

Try to love what you do. I am very selective to choose what to do
next, what to learn, what to accomplish. I will be very regret if I
lost my time unwisely.

I try to 'make everything counts'. As I told you about this concept.
I will try to avoid useless things, and make everything I do counted.

Try to build the map of your life. run for your goals. build your
good habit.

Have a great day.
